### PR TITLE
feat: Chat message attachment preview

### PR DESCRIPTION
**Pull request by thelukewalton**
https://jira.zebra.com/browse/UX-961

### CODE REVIEW

**Review by mikecoomber — COMMENTED** [review]
- I don't think we should be able to preview media that hasn't loaded
- Can we change the background of the preview to have an opacity animation instead of coming in from the right? it just looks a bit strange

**Comment by thelukewalton** [comment]
> * I don't think we should be able to preview media that hasn't loaded
> 
>     * Can we change the background of the preview to have an opacity animation instead of coming in from the right? it just looks a bit strange

* Whilst media hasn't loaded, we show a spinner currently. What do you suggest otherwise?
* I can change it to not come in from the right, but it is putting a new page onto the route, rather than something ontop of the current page, so I don't know how to do opacity in that situation

**Comment by mikecoomber** [comment]
> > * I don't think we should be able to preview media that hasn't loaded
> >   
> >   * Can we change the background of the preview to have an opacity animation instead of coming in from the right? it just looks a bit strange
> 
> * Whilst media hasn't loaded, we show a spinner currently. What do you suggest otherwise?
> * I can change it to not come in from the right, but it is putting a new page onto the route, rather than something ontop of the current page, so I don't know how to do opacity in that situation

I meant more for these messages 
image
When I first ran it I could click on them and it would give me a full screen preview just with the error text but I can't replicate that any more so maybe it's not an issue

Yeah I think we should take out the page animation

**Comment by thelukewalton** [comment]
> hen I first ran it I could click on them and it would give me a full screen preview just with the error text but I can't replicate that any more so maybe it's not an issue

* That is part CORS issue, and part UX-941 which will replace the error widget with the download attachment widget.
* 👍

**Review by mikecoomber — APPROVED** [review]

**Pull request merged**
